# A  CRD to deploy  easy cicd  from a git repo
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: easycicd.rootcloud.com
spec:
  scope: Namespaced
  group: rootcloud.com
  versions:
    - name: v1
      served: true
      storage: true
  names:
    kind: EasyCicd
    plural: easycicd
    singular: easycicd
    shortNames:
      - cd
  validation:
   # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required:
            - resourceVersion
            - replicas
            - gitrepo
            - gitbranch
            - type
          properties:
            resourceVersion: #----必须是整数，最小值必须为0，最大值必须为9999
              type: integer
              minimum: 0
              maximum: 9999
            replicas: #----必须是整数，最小值必须为0，最大值必须为5
              type: integer
              minimum: 0
              maximum: 5
            gitrepo: #--必须是字符串，并且必须是正则表达式所描述的形式
              type: string
              pattern: '^((http://)|(https://))?([a-zA-Z0-9]([a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,6}(/)'
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      priority: 0
      JSONPath: .spec.replicas
      description: Amount of replicas
    - name: GitRepo
      type: string
      priority: 0
      JSONPath: .spec.gitrepo
      description: Git repository with web content
    - name: GitBranch
      type: string
      priority: 0
      JSONPath: .spec.gitbranch
      description: Git branch with repo
    - name: Type
      type: string
      priority: 0
      JSONPath: .spec.type
      description: application language type